### ISSUE TITLE
[Refactor] 예약 상세보기 UI 변경사항 반영

### ISSUE THREAD

**Issue by woongaaaa** [MEME-UMC/MEME_iOS#101]
## 💡 Issue

UI 리팩토링 - 예약 상세보기 VC 변경사항 반영
SingleArtistReservationManageViewController -> SingleReservationManageViewController로 이름 변경 (아티스트, 모델 모두 사용)

## 📝  Todo
- [ ] VC명 바꾸기
- [ ] 디자인 수정사항 반영
- [ ] API 반영 (나중)
- [ ] (아티스트) '포트폴리오 관리'에서 포트폴리오 클릭 시 '포트폴리오 미리보기' 화면으로 전환
