### ISSUE TITLE
[Refactor] 아티스트 포트폴리오 수정/추가 VC 리팩토링

### ISSUE THREAD

**Issue by woongaaaa** [MEME-UMC/MEME_iOS#119]
## 💡 Issue

아티스트 포트폴리오 수정/추가 VC 리팩토링

## 📝  Todo
- [x] 이미지 피커 변경
- [x] 이미지뷰 콜렉션 뷰로 구조 변경
- [ ] 일정 관리 추가 (디자인 아직 안 나옴)
- [ ] API 호출 async+await 사용
