### ISSUE TITLE
[Todo] 배포 전 할 일

### ISSUE THREAD

**Issue by taipaise** [MEME-UMC/MEME_iOS#125]
### 회원 관련
- [ ] 자체 로그인 api 연결 **(민지)**
- [ ] 이메일 찾기 api 연결 **(민지)**
- [ ] 비밀번호 찾기 api 연결 **(민지)**
- [ ] 회원탈퇴 구현 (각 소셜 서비에서 제공하는 api를 이용해서 구현해야 함) **(민지)**

### 홈 화면 (모델)
- [ ] 변경된(될) 전체 예약 보기 api 스펙에 맞게 네트워크 코드 수정 **(민지)**
- [ ] 변경된 아티스트 프로필 조회api 스펙에 맞게 네트워크 코드 수정 **(민지)**
### 예약하기(모델)
- [ ] 변경된 예약 정보 조회 api 스펙에 맞게 코드 수정. (네트워크 코드 + 화면 표시 로직) **(민지)**
### 마이페이지(모델)
- [ ] 관심 아티스트 api 연결 **(아영)**
- [ ] 관심 메이크업 api 연결 **(아영)**
- [ ] 탈퇴 로직 수정 **(아영)**
### 프로필 완성하기 화면(아티스트)
- [ ] 이메일 입력, 인스타그램 아이디 입력 필드 추가 **(아영)**
- [ ] 이메일 인증 api 연결 **(아영)**

### 포트폴리오 관리(아티스트)
- [x] 변경된 셀에 맞게 cv 레이아웃 변경 **(채웅)**

### 일정 관리 화면 (아티스트) -> 제일 오래 걸릴 듯
- [ ] 일정 관리 첫 진입 화면 구현 **(아영)**
- [ ] 일정 설정 로직 구현 **(아영)**
- [ ] 등록 완료(상세 시간 설정) 화면 ui 구현 **(채웅)**
- [ ] 상세 시간 설정 로직 구현 **(채웅)**
- [ ] 상세 시간 설정 api 연결 **(채웅)**

### 모델 아티스트 공통
- [ ] 예약관리 상세 화면 ui 수정 **(채웅)**
- [ ] 예약관리 상세 화면 api 연결 **(채웅)**
- [ ] 알림 api 연결 **(민지)**
- [ ] 푸시 알림 fcm 연동 (선우랑 작업) **(민지)**

### 이미지 처리 관련
- [ ] 이미지를 s3에 직접 업로드 하는 로직이 구현되어있지 않음 **(민지)**
