### ISSUE TITLE
[Feat] Model View 관련 ReservationAPI 연결

### ISSUE THREAD

**Issue by wjdalswl** [MEME-UMC/MEME_iOS#18]
## 💡 Issue

- Model View 관련 ReservationAPI 연결
## 📝  Todo

- [x] 아티스트 예약가능 장소 조회
- [x] 아티스트 예약가능 시간 조회
- [x] 예약하기
- [x] 모델 예약 조회
