### ISSUE TITLE
[Fix] ModelView 관련 사소한 수정

### ISSUE THREAD

**Issue by wjdalswl** [MEME-UMC/MEME_iOS#39]
## 💡 Issue
ModelView 관련 사소한 수정 여러개

## 📝  Todo
- [ ] 이미지 정사각형 맞게 불러오기
- [ ] 포트폴리오 뒷면 이미지 세개 뜨는지 확인
- [ ] API 호출시 넣는 모델 id 값 수정
