### ISSUE TITLE
[Fix] 모델 회원 가입 오류 수정 및 UI 수정

### ISSUE THREAD

**Issue by taipaise** [MEME-UMC/MEME_iOS#56]
## 💡 Issue

- 모델 회원가입이 진행되지 않는 문제 수정

## 📝  Todo
- [ ] 키보드 return 버튼 tap 시 내려가도록 수정
- [ ] 닉네임 입력 label 문구 수정
- [ ] navigationBar hidden 적용
