### ISSUE TITLE
[Feat] 아티스트, 포트폴리오 CRUD 이미지 처리

### ISSUE THREAD

**Issue by woongaaaa** [MEME-UMC/MEME_iOS#57]
## 💡 Issue

아티스트, 포트폴리오 CRUD 이미지 처리(일단 1개씩)
UI 관련 세부 수정도 필요

## 📝  Todo
- [ ] 아티스트 프로필 조회 프로필 이미지
- [ ] 포트폴리오 CRUD 이미지 처리
- [ ] UI 관련 세부 수정
