### ISSUE TITLE
Core 폴더 정리

### ISSUE THREAD

**Issue by taipaise** [MEME-UMC/MEME_iOS#90]
## 💡 Issue

Core 폴더 Model 정리
## 📝  Todo
- [ ] 공통 model 분류
- [ ] 모델 model 분류
- [ ] 아티스트 model 분류
- [ ] manager class 분류
- [ ] protocol 분류
