### ISSUE TITLE
[Fix] 네비게이션 바 수정

### ISSUE THREAD

**Issue by taipaise** [MEME-UMC/MEME_iOS#93]
## 💡 Issue

- 네비게이션 바 수정
## 📝  Todo
- [x] 네비게이션 바 색상 수정
- [x] 다크모드에서도 흰색으로 나오게 수정
- [x] title label 커스텀
